name: 'Composite Action Template'
description: 'Get started with Composite actions'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  greet:
    description: 'The word we greeted you'
    value: ${{ steps.greet.outputs.word }}
runs:
  using: "composite"
  steps:
    - id: greet
      run: |
        GREET="Hello ${WHO}"
        echo "${GREET}"
        echo "${GREET}" > greet.txt
        echo "::set-output name=word::${GREET}"
      shell: bash
      env:
        WHO: ${{ inputs.who-to-greet }}
branding:
  icon: 'award'  
  color: 'green'
