name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test-without-parameters:
    strategy:
      fail-fast: false
      matrix:
        # Runs on all supported runners
        # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
        os: [ ubuntu-20.04, ubuntu-18.04, windows-2022, windows-2019, windows-2016, macos-11, macos-10.15 ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 1
    defaults:
      run:
        # powershell might be better on windows-*
        shell: bash

    steps:
      - uses: actions/checkout@v3
      - id: action
        uses: ./
      - run: test "${GREET}" = "Hello World"
        env:
          GREET: ${{ steps.action.outputs.greet }}
      - run: test "$(cat greet.txt)" = "Hello World"

  test-with-parameters:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, ubuntu-18.04, windows-2022, windows-2019, windows-2016, macos-11, macos-10.15 ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 1
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
      - id: action
        uses: ./
        with:
          who-to-greet: composite action
      - run: test "${GREET}" = "Hello composite action"
        env:
          GREET: ${{ steps.action.outputs.greet }}
      - run: test "$(cat greet.txt)" = "Hello composite action"

  # Make up matrix statuses into a status for status checks in branch protection rules
  test-passing:
    needs: [ test-without-parameters, test-with-parameters ]
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - run: echo "All tests have passed."
